config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Image upload to users show page
  resources :users do
  	member do
  		put 'updatejson'
  	end
  end	
  
  # Image upload to hike show page
  resources :hikes do
    member do
      put 'updatejson2'
    end
  end 
  
  root to: 'hikes#index'
  get 'secure' => 'users#secure'
  post '/hikes/search' => 'hikes#search'
  


end

#               	Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#        user_registration POST   /users(.:format)               devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                          PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                    users GET    /users(.:format)               users#index
#                          POST   /users(.:format)               users#create
#                 new_user GET    /users/new(.:format)           users#new
#                edit_user GET    /users/:id/edit(.:format)      users#edit
#                     user GET    /users/:id(.:format)           users#show
#                          PATCH  /users/:id(.:format)           users#update
#                          PUT    /users/:id(.:format)           users#update
#                          DELETE /users/:id(.:format)           users#destroy
#                    hikes GET    /hikes(.:format)               hikes#index
#                          POST   /hikes(.:format)               hikes#create
#                 new_hike GET    /hikes/new(.:format)           hikes#new
#                edit_hike GET    /hikes/:id/edit(.:format)      hikes#edit
#                     hike GET    /hikes/:id(.:format)           hikes#show
#                          PATCH  /hikes/:id(.:format)           hikes#update
#                          PUT    /hikes/:id(.:format)           hikes#update
#                          DELETE /hikes/:id(.:format)           hikes#destroy
#                     root GET    /                              users#index
#                   secure GET    /secure(.:format)              users#secure

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/hike.rb
class Hike < ActiveRecord::Base
	has_and_belongs_to_many :users
	geocoded_by :name
	after_validation :geocode  
# Search Feature
def self.search(search)
  where("name ILIKE ? OR location ILIKE ?", "%#{search}%",  "%#{search}%") 

end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	# has_and_belongs_to_many :hikes
 	validates :first_name, presence: false
 	validates :last_name, presence: false
 	validates :about, presence: false
 	# validates :image_urls, presence: false

 has_and_belongs_to_many :hikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions
  # redirect user to hike page if they don't have permission to edit profile
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_url, :alert => exception.message
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController

  def home
  	@hikes = Hike.all
  end

	def index 
		@hikes = Hike.all
		if params[:search]
    	@hikes = Hike.search(params[:search])
  	else
    	@hikes = Hike.all
  end

	def new 
		@hike = Hike.new
		 puts "================="
      puts "New Hike Created"
      puts "================="
	end

	def create
		@hike = Hike.create(hikes_params)
		redirect_to hikes_path
	end

	def edit
		@hike = Hike.find(params[:id])
		puts "======================"
    puts " Hike Information was edited"
    puts "======================"
	end

	def show
		@hike = Hike.find(params[:id])	
	end
	
	def update
		@hike = Hike.find(params[:id])
		@hike.update_attributes(hike)
		redirect_to hikes.path
		puts "====================="
    puts "Hike info was updated"
    puts "====================="
	end

	def updatejson2
    hike = Hike.find(params[:id])
    puts params[:img_url]
    hike.img_url = params[:img_url]
    hike.save
    render json2: hike
  end

	def destroy
		@hike = Hike.find(params[:id])
		@hike.destroy
		redirect_to hikes_path 
	end
end

private

	def hikes_params
		params.require(:hike).permit(:name, :location, :description, :img_url, :lat, :long)
	end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
    before_action :authenticate_user!, only: :secure
    def index
	    if current_user
	        puts "I'm logged in as #{current_user.email}"
	    else 
	        puts "I'm not logged in"
	    end
    end

     def secure
      id = current_user.id
      user = User.find(id)

      puts "============"
      p user
      puts "============"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: :secure

    
    def index
      @users = User.all
    end

    def create
      @user = User.create(user_params)
      redirect_to users_path
    end

    def new
      @user = User.new
      puts "================="
      puts "New Info Created"
      puts "================="
    end

    def edit
      @user = User.find(params[:id])
       
      puts "======================"
      puts "Information was edited"
      puts "======================"
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update_attributes(user_params)
      redirect_to User.find(params[:id])
      puts "====================="
      puts "User info was updated"
      puts "====================="
    end

    def updatejson
      user = User.find(params[:id])
      puts params[:image]
      user.image = params[:image]
      user.save
      render json: user
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect to users_path
    end

     def secure
      id = current_user.id
      user = User.find(id)
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :about, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hikes/_form.html.erb
<%=form_for  (Hike.new) do |form| %>
	
	Name: <br> <%= form.text_field :name %> <br>
	Location:<br> <%= form.text_field :location %> <br>
	About: <br><%= form.text_area :description %> <br>
	Image:<br> <%= form.text_field :img_url %> <br> 

	<%= form.submit %>

<% end %>



<!-- <form id="up-form">
  <input type="file" multiple />
  <button type="submit">Upload</button>
</form> -->

app/views/hikes/index.html.erb
<% if user_signed_in? %>

<% end %>
<!-- Slidshow-only display content if no user is signed in -->
<% if !user_signed_in? %>


<a href="/hikes#hikes_container"><div class="pull_up">Explore Hikes</div></a>


	<script type="text/javascript">
	function slideSwitch() {
	    var $active = $('#slideshow IMG.active');

	    if ( $active.length == 0 ) $active = $('#slideshow IMG:last');

	    // use this to pull the images in the order they appear in the markup
	    var $next =  $active.next().length ? $active.next()
	        : $('#slideshow IMG:first');

	    $active.addClass('last-active');

	    $next.css({opacity: 0.0})
	        .addClass('active')
	        .animate({opacity: 1.0}, 1000, function() {
	            $active.removeClass('active last-active');
	        });
	}
	$(function() {
	    setInterval( "slideSwitch()", 5000 );
	});
	</script>



</div>
	<div id="slideshow">
	    <img src="http://www.denalihostel.com/images/employee_hike.jpg" alt="Slideshow Image 1" class="active" />
	    <img src="http://images.fineartamerica.com/images-medium-large-5/hiker-silhouette-lane-erickson.jpg" alt="Slideshow Image 2" />
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/McKinley_and_a_hiker.jpg/1280px-McKinley_and_a_hiker.jpg" alt="Slideshow Image 3" />
	    <img src="http://stayhealthyla.com/wp-content/uploads/2016/03/191013.jpg" alt="Slideshow Image 4" />
	</div>
	
<% end %>

<!-- Iterate through the hikes -->
<div id="hikes_container"></div>
<div class="index_flex">
	<div class="hikes_container">
		<h1>Hikes</h1>
		<% @hikes.each do |hike| %>
		<h2><%= link_to hike.name, hike_path(hike.id) %></h2>
		<!-- <h2><%= hike.location %></h2> -->
		<!-- <p><%= hike.description%></p> -->
	  <% end %>
	  </div>
	<hr>

	<!-- Google Maps Container -->
	<div style='width: 800px;'>
	  <div id="map" class="index_map" ></div>
	</div>
</div>

<!-- Google Maps Script, Shows all the hikes based on long/lat coordinates -->
	 <script type="text/javascript">
	<% @hikes.each do |hike| %>
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers([
	    {
	      "lat": <%=hike.latitude%>,
	      "lng": <%=hike.longitude%>,
	      "infowindow": "<%=hike.name%>"
	    }
	  ]);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	  handler.getMap().setZoom(2);
	});
	//using the index provided by jquery.each()  

	 <% end %>
	</script>

app/views/hikes/new.html.erb
<div class="edit_container">
<h2>Add a Hike</h2>


<%= render :partial => 'form' %>

<!-- 
<form id="up-form">
  <input type="file" multiple /> <br>
  <button type="submit">Upload</button> -->
<!--   send upload data to hikes controller somehow -->
<!-- </form> -->
</div>

app/views/hikes/show.html.erb
<div class="show_info">
  <h3><%= @hike.name %>, <%= @hike.location %></h3>
  <h3></h3>
  <p><%= @hike.description %></p>
</div>

<div class="show_flex">

<img class="show_img" src=" <%= @hike.img_url %>"> 
<br>
<!-- Photo upload through Ospry -->
<!-- <form id="up-form">
  <input type="file" multiple />
  <button type="submit">Upload</button>
</form> -->

<!-- Google Map div -->
<div style='width: 800px;'>
  <div class= "show_map" id="map" ></div>
</div> <!-- ends Google Maps div -->
  <script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
      "lat": <%=@hike.latitude%>,
      "lng": <%=@hike.longitude%>,
      "infowindow": "<%=@hike.latitude%>, <%=@hike.longitude%>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(9);
  });
  </script>
</div> <!-- ends flex container -->

<!-- Links to list of all hikes -->
<a href="/hikes#hikes_container"><div class="hikes_link">
Explore More Hikes</div></a>



<!-- Comments -->
<% if user_signed_in? %>
<div class="comments">
  <h3>Leave A Commnet</h3>
  <div id="disqus_thread"></div>
</div>

<hr>

<footer> <%= link_to 'Delete This Hike', @hike, :method => 'delete', data: { confirm: 'Are you sure?' } %></footer>

<% else %>

<div class="hike_show_footer">
<h5><a href="/users/sign_in">Log in</a> or <a href="/users/sign_up">sign up</a> to comment on this hike.</a></h5>
</div>







<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
  <title>Ruby on Trails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- ospry for image upload -->
<script src="https://code.ospry.io/v1/ospry.js"></script>

<!-- Google Maps -->
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

</head>
<body>
<h1 class="site_title"><a href="/hikes">Ruby on Trails</a></h1>


<!-- login bar -->

<p>
<% if user_signed_in? %>
<!-- if logged in -->
<div class="nav_bar_user">
  Welcome <strong><%= current_user.first_name %></strong>  <br>
  <%= link_to "Profile", current_user, :class => "navbar-link" %> |
  <%= link_to 'Explore Hikes', hikes_path(@hikes), :class => 'navbar-link' %> |
  <%= link_to 'Find Hikers', users_path(@users), :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
  </div>
  <!-- Search Bar -->
  <%= form_tag(hikes_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Hikes" %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>

<% else %>
<!-- if logged out -->
<div class="nav_bar">
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> 
    <%= form_tag(hikes_path, :method => "get", id: "search-form") do %>
</div>
  
    <% end %>
  <% end %>
</div>
</p>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%=form_for @user do |form| %>
	
	Email: <br><div class="user_email"><%= form.text_field :email %> </div> <br>
	First Name:<br> <%= form.text_field :first_name %> <br>
	Last Name:<br> <%= form.text_field :last_name %> <br>
	About:<br> <%= form.text_area :about %> <br>
	

	<%= form.submit %>

<% end %>

app/views/users/edit.html.erb
<div class="edit_container">
<h2>Edit User</h2>

<%= render :partial => 'form' %>

<%= link_to "Change email and password", edit_user_registration_path, :class => 'navbar-link' %> 

</div>

app/views/users/index.html.erb
<!-- <h4>Home Page for sign in or sign up</h4> -->
<div class="hikers_list">
	<h1>Hikers </h1>
	<% @users.each do |user| %>
	<a href="/users/<%= user.id %>"><h5><%= user.first_name %> <%= user.last_name %> </h5></a> <br>
		<img class= "user_index_image" src=" <%= user.image %>">
		<hr>
	<% end %>
</div>

app/views/users/secure.html.erb
<h1>Users profile- Only a logged in person can see this</h1>

app/views/users/show.html.erb
<div class="show_info">
	<h3><%= @user.first_name %> <%= @user.last_name %></h3>
	<img class="user_show_image" src=" <%= @user.image %>"> 

<br>
	<h5>About me:</h5><p><%= @user.about %></p>
</div>

<br>
<hr>

	
<div class="photo_upload">
<form id="up-form">
	<h5>Change Your Profile Photo</h5>

  <input type="file" multiple /> 
  <button type="submit">Upload</button>
<!--   send upload data to Users controller somehow -->
</form>


<a href="/hikes/new"><h5>Add a Hike</h5></a> 

<a href="/users/<%= @user.id %>/edit"><h5>Update Information</h5></a>

</div>
<!--  <h5>Hikes</h5>
<% @user.hikes.each do |hike| %>
<li>Name<%= hike.name %></li>
<%= link_to "Show", user_hike_path(user_id: @user.id, id: hike.id) %>

<% end %>  -->